version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./setupConfig.js:/app/setupConfig.js
      - ./Backend/db:/app/backend/db
      - ./logs:/app/backend/logs
    healthcheck:
      test: 
        - "CMD-SHELL"
        - "curl -f http://localhost:3001/health || exit 1 && curl -f http://localhost:3000/health || exit 1"
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - NODE_ENV=production