const path = require('path');

/**
 * GENERATED FILE - do not edit by hand. Regenerated by
 * scripts/generate-frontend-registry.js after every frontend build, from
 * whatever is actually in frontend/build at that time. See that script for
 * why this file exists (pkg's static-scan asset detection workaround).
 */
function registerFrontendAssets() {
    return [
        path.join(__dirname, '../../frontend/build', "asset-manifest.json"),
        path.join(__dirname, '../../frontend/build', "index.html"),
        path.join(__dirname, '../../frontend/build', "old-computer.png"),
        path.join(__dirname, '../../frontend/build', "static", "css", "265.ffdda26b.chunk.css"),
        path.join(__dirname, '../../frontend/build', "static", "css", "265.ffdda26b.chunk.css.map"),
        path.join(__dirname, '../../frontend/build', "static", "css", "285.1a8233a6.chunk.css"),
        path.join(__dirname, '../../frontend/build', "static", "css", "285.1a8233a6.chunk.css.map"),
        path.join(__dirname, '../../frontend/build', "static", "css", "416.671b0089.chunk.css"),
        path.join(__dirname, '../../frontend/build', "static", "css", "416.671b0089.chunk.css.map"),
        path.join(__dirname, '../../frontend/build', "static", "css", "476.3e1e2a64.chunk.css"),
        path.join(__dirname, '../../frontend/build', "static", "css", "476.3e1e2a64.chunk.css.map"),
        path.join(__dirname, '../../frontend/build', "static", "css", "694.45582acf.chunk.css"),
        path.join(__dirname, '../../frontend/build', "static", "css", "694.45582acf.chunk.css.map"),
        path.join(__dirname, '../../frontend/build', "static", "css", "840.f46bc5e0.chunk.css"),
        path.join(__dirname, '../../frontend/build', "static", "css", "840.f46bc5e0.chunk.css.map"),
        path.join(__dirname, '../../frontend/build', "static", "css", "main.6c80ee3c.css"),
        path.join(__dirname, '../../frontend/build', "static", "css", "main.6c80ee3c.css.map"),
        path.join(__dirname, '../../frontend/build', "static", "js", "170.7453c72b.chunk.js"),
        path.join(__dirname, '../../frontend/build', "static", "js", "170.7453c72b.chunk.js.LICENSE.txt"),
        path.join(__dirname, '../../frontend/build', "static", "js", "170.7453c72b.chunk.js.map"),
        path.join(__dirname, '../../frontend/build', "static", "js", "265.38b519cc.chunk.js"),
        path.join(__dirname, '../../frontend/build', "static", "js", "265.38b519cc.chunk.js.map"),
        path.join(__dirname, '../../frontend/build', "static", "js", "285.71061a97.chunk.js"),
        path.join(__dirname, '../../frontend/build', "static", "js", "285.71061a97.chunk.js.map"),
        path.join(__dirname, '../../frontend/build', "static", "js", "416.978bbaeb.chunk.js"),
        path.join(__dirname, '../../frontend/build', "static", "js", "416.978bbaeb.chunk.js.map"),
        path.join(__dirname, '../../frontend/build', "static", "js", "476.25d6e911.chunk.js"),
        path.join(__dirname, '../../frontend/build', "static", "js", "476.25d6e911.chunk.js.map"),
        path.join(__dirname, '../../frontend/build', "static", "js", "619.18fc313b.chunk.js"),
        path.join(__dirname, '../../frontend/build', "static", "js", "619.18fc313b.chunk.js.map"),
        path.join(__dirname, '../../frontend/build', "static", "js", "694.cfdc6845.chunk.js"),
        path.join(__dirname, '../../frontend/build', "static", "js", "694.cfdc6845.chunk.js.map"),
        path.join(__dirname, '../../frontend/build', "static", "js", "840.d8c1a786.chunk.js"),
        path.join(__dirname, '../../frontend/build', "static", "js", "840.d8c1a786.chunk.js.map"),
        path.join(__dirname, '../../frontend/build', "static", "js", "95.a02708ee.chunk.js"),
        path.join(__dirname, '../../frontend/build', "static", "js", "95.a02708ee.chunk.js.map"),
        path.join(__dirname, '../../frontend/build', "static", "js", "990.0f5e967c.chunk.js"),
        path.join(__dirname, '../../frontend/build', "static", "js", "990.0f5e967c.chunk.js.map"),
        path.join(__dirname, '../../frontend/build', "static", "js", "main.1e1b69aa.js"),
        path.join(__dirname, '../../frontend/build', "static", "js", "main.1e1b69aa.js.LICENSE.txt"),
        path.join(__dirname, '../../frontend/build', "static", "js", "main.1e1b69aa.js.map"),
        path.join(__dirname, '../../frontend/build', "static", "media", "boxicons.65a8ce52fc5427e8f94d.eot"),
        path.join(__dirname, '../../frontend/build', "static", "media", "boxicons.9e2b21b135bc7d4c803f.svg"),
        path.join(__dirname, '../../frontend/build', "static", "media", "boxicons.d12afc36557395143e4b.woff"),
        path.join(__dirname, '../../frontend/build', "static", "media", "boxicons.db9ddb1898dbd76badca.ttf"),
        path.join(__dirname, '../../frontend/build', "static", "media", "boxicons.df635aaf04cd75132f62.woff2"),
    ];
}

module.exports = { registerFrontendAssets };
